export enum MusicalGenres {
    ROCK = "ROCK",
    HIP_HOP = "HIP_HOP",
    HEAVY_METAL = "HEAVY_METAL",
    FOLK = "FOLK",
    JAZZ = "JAZZ",
    J_POP = "J_POP",
    ELECTRONIC = "ELECTRONIC",
    CLASSICAL = "CLASSICAL",
    COUNTRY = "COUNTRY",
    PUNK = "PUNK",
    GOTH = "GOTH",
    OPERA = "OPERA",
    TECHNO = "TECHNO",
    RAP = "RAP",
}
export enum MusicalInstrument {
    GUITAR = "GUITAR",
    PIANO = "PIANO",
    DRUMS = "DRUMS",
    BASS = "BASS",
    VIOLIN = "VIOLIN",
    FLUTE = "FLUTE",
    SAXOPHONE = "SAXOPHONE",
    TRUMPET = "TRUMPET",
    TROMBONE = "TROMBONE",
    HARMONICA = "HARMONICA",
    ACCORDION = "ACCORDION",
    HARP = "HARP",
    UKULELE = "UKULELE",
    CELLO = "CELLO",
    VIOLA = "VIOLA",
    CLARINET = "CLARINET",
    OBOE = "OBOE",
    TUBA = "TUBA",
    ORGAN = "ORGAN",
    XYLOPHONE = "XYLOPHONE",
    SING = "SING",
    PANDURI = "PANDURI",
    SALAMURI = "SALAMURI",
    DOLI = "DOLI",
}